# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/terminalStopwatch',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/terminalStopwatch',
                'lib_path': 'terminalStopwatch'},
  'syms': {'terminalStopwatch.core': {'terminalStopwatch.core.foo': ('core.html#foo', 'terminalStopwatch/core.py')}}}
