# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/stopwatch2.ipynb.

# %% auto 0
__all__ = ['TimeDisplay', 'Stopwatch', 'StopwatchApp']

# %% ../nbs/stopwatch2.ipynb 4
from textual.app import App, ComposeResult
from textual.containers import Container
from textual.widgets import Button, Header, Footer, Static

# %% ../nbs/stopwatch2.ipynb 7
class TimeDisplay(Static):
    """A widget to display elapsed time."""

# %% ../nbs/stopwatch2.ipynb 10
class Stopwatch(Static):
    """A stopwatch widget."""

    def compose(self) -> ComposeResult:
        """Create child widgets of a stopwatch."""
        yield Button('Start', id='start', variant='success')
        yield Button('Stop', id='stop', variant='error')
        yield Button('Reset', id='reset')
        yield TimeDisplay('00:00:00.00')

# %% ../nbs/stopwatch2.ipynb 13
class StopwatchApp(App):
    """A Textual app to manage stopwatches."""

    BINDINGS = [('d', 'toggle_dark', 'Toggle dark mode')]

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Footer()
        yield Container(Stopwatch(), Stopwatch(), Stopwatch())
    
    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.dark = not self.dark

# %% ../nbs/stopwatch2.ipynb 17
#| eval: false
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

if __name__ == '__main__' and not IN_NOTEBOOK:
    app = StopwatchApp()
    app.run()
