# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/stopwatch1.ipynb.

# %% auto 0
__all__ = ['StopwatchApp']

# %% ../nbs/stopwatch1.ipynb 4
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer

# %% ../nbs/stopwatch1.ipynb 7
class StopwatchApp(App):
    """A Textual app to manage stopwatches."""

    BINDINGS = [('d', 'toggle_dark', 'Toggle dark mode')]

    def compose(self) -> ComposeResult:
        """Create child widgets for the app."""
        yield Header()
        yield Footer()
    
    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.dark = not self.dark

# %% ../nbs/stopwatch1.ipynb 14
#| eval: false
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

if __name__ == '__main__' and not IN_NOTEBOOK:
    app = StopwatchApp()
    app.run()
